### ISSUE TITLE
gxref should ask to create database if not found

### ISSUE THREAD

**Issue by jockej** [dedi/gxref#2]
Hello!
I've just found gxref, and I find it awesome! I would like to use it to replace ggtags in my daily use, so if it's OK with you I'd like to contribute some things.

I created this issue mainly to introduce myself, but if I get your OK I'll implement it and make a pull request :)

**Comment by dedi** [comment]
Hello Joakim

First of all, sorry for the late response. I've been away for awhile. Of
course it would be great if you still want to contribute to the package. To
be honest, it's a bit simplistic right now - it was written mostly because
I've switched to Emacs 25, and wanted to try out the new and unified xref
mechanism. Once I got the library to be good enough for my own use, I
stopped working on it. Your email actually gives me some new energy to get
back to it. So thank you already.

If you would like to contribute, let's discuss the features you want to
add, just to make sure we're on the same page. I'll be happy to add
anything that will make the library more useful, but if you have ideas
regarding new features that could be added, let's talk about them before
you jump into coding. And of course, bug fixes are always welcome.

Regarding style - I'm not really an Elisp programmer, but I do try to keep
the code reasonably tidy and documented. Also, Melpa has a few guidelines
about writing packages that go into the their repository. they're pretty
simple - basically it's a 'don't break anything' rule. But we need to
adhere to these guidelines.

Anyway, thank you for wanting to join in.
Dedi

**Comment by jockej** [comment]
No problem!

Well, I think it works really well right now actually. I just think it would be nice to be a little "dwim-ish". For example (this issue) it would be nice if gxref could ask to create the database if it doesn't exist, and I think what would be even nicer is if we could ask to use a specific label depending on mode.

Basically I have two use cases in mind:

1. c-mode, c++-mode, java-mode...
I press M-. (there is no global database yet). gxref could then ask me:
"No database found, create now? (Y/n)"
I would press y or RET and the database would be built.

2. cobol-mode, fortran90-mode, sh-mode etc...
I press M-. (there is no global database yet). gxref could then ask me:
"No database found, create now? (Y/n)"
I press y.
gxref asks me: "Use universal-ctags backend? (Y/n)" since the current buffer is a cobol-mode buffer.
I press y again.
gxref asks: "Add gxref-gtags-label='new-ctags' to dir-locals.el? (y/n)".
I press y again.
(maybe go through all open buffers in current project and update their dir-locals).

The point is it would be great to use gxref for all kinds of languages, which can be done via the different global backends. I could do this mannually by writing a .dir-locals.el in the project root, setting gxref-gtags-label in it and then manually calling gxref-create-db, but I think it would be nice to automate this.

These are just ideas I'm throwing out there :) WDYT?

**Comment by jockej** [comment]
Ok, I whitdraw all the stuff I said about "dwimish" above :) After seeing [this](https://github.com/yoshizow/global-pygments-plugin/blob/master/sample.globalrc) I understand that the choice of parser should be done in the .globalrc file.

I have submitted a pull request for this issue (creating the database if it does not exist) though.

**Comment by jockej** [comment]
Sorry, but I've changed my mind again. I think it's better do what is mentioned in the documentation and add gxref as a backend in all modes, and only use it if there is a database or gxref-project-root-dir is set. This obviously means we should just return nil if no database is found. So I will close this issue and pull request.

Sorry for the noise!
